# Generated by Django 2.0 on 2019-03-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leaf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaf_image', models.FileField(blank=True, null=True, upload_to='', verbose_name='Add Photo to Article')),
            ],
        ),
    ]
