# Generated by Django 2.0 on 2019-03-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaf',
            name='leaf_data',
            field=models.CharField(default='abc', max_length=2500, verbose_name='Leaf Data'),
            preserve_default=False,
        ),
    ]
