# Generated by Django 2.0 on 2019-03-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaf', '0002_leaf_leaf_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaf',
            name='leaf_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Add Photo of the Leaf'),
        ),
    ]
